name: anchiano
description: Anchiano frontend in Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ---- State management ----
  flutter_bloc: ^9.0.0

  # ---- HTTP ----
  http: ^1.2.2

  # ---- Secure storage ----
  flutter_secure_storage: ^9.0.0

  # ---- Internationalization ----
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # ---- Utils ----
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  # ARB files voor i18n
  generate: true
  assets:
    - l10n/
